apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        splunk_observability_access_token: "{{ `{{ .splunkObservabilityAccessToken }}` }}"
        splunk_platform_hec_token: "{{ `{{ .splunkPlatformToken }}` }}"
  data:
    - secretKey: splunkObservabilityAccessToken
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.properties.splunkObservabilityAccessToken }}
    - secretKey: splunkPlatformToken
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.properties.splunkPlatformToken }}