apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        hecToken: "{{ `{{ .hecToken }}` }}"
  data:
    - secretKey: hecToken
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.property }}