---
# Source: external-secrets-operator/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
# Source: external-secrets-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-operator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::125980734123:role/ExternalSecretsRole
---
# Source: external-secrets-operator/templates/operatorconfig.yaml
apiVersion: externalsecrets.operator.openshift.io/v1alpha1
kind: ExternalSecretsOperator
metadata:
  name: cluster
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
---
# Source: external-secrets-operator/templates/subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
