clusterName: ocp-aws-acm-ocp1

splunkObservability:
  realm: us1

splunkPlatform:
  endpoint: https://prd-p-6c0ti.splunkcloud.com/services/collector
  index: main
  metricsIndex: metrics
  tracesIndex: traces
  logsEnabled: true
  metricsEnabled: false
  tracesEnabled: false

gateway:
  enabled: true