apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: {{ .Values.externalSecretsConfig.name }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    app: external-secrets-operator
    app.kubernetes.io/name: {{ .Values.externalSecretsConfig.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
{{- if .Values.externalSecretsConfig.controllerConfig.create }}
  controllerConfig:
    networkPolicies:
{{- toYaml .Values.externalSecretsConfig.controllerConfig.networkPolicies | nindent 6 }}
{{- else }}
  {}
{{- end }}