apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ .Values.operatorNamespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountId }}:role/ExternalSecretsRole
