operatorNamespace: external-secrets-operator
operandNamespace: external-secrets

operatorGroup:
  name: openshift-external-secrets-operator
  targetNamespaces: []

subscription:
  name: openshift-external-secrets-operator
  packageName: openshift-external-secrets-operator
  channel: stable-v1
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  startingCSV: external-secrets-operator.v1.0.0

awsAccountId: "125980734123"