operatorNamespace: external-secrets-operator
operandNamespace: external-secrets

operatorGroup:
  name: openshift-external-secrets-operator
  targetNamespaces: []

subscription:
  name: openshift-external-secrets-operator
  packageName: openshift-external-secrets-operator
  channel: stable-v1
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

externalSecretsConfig:
  name: cluster
  controllerConfig:
    create: true
    networkPolicies:
      - componentName: ExternalSecretsCoreController
        name: allow-external-secrets-egress
        egress:
          - {}