namespace: observability

monitoringStack:
  name: monitoring
  prometheus:
    replicas: 2
    retention: 7d
    storage:
      size: 50Gi
      storageClassName: ""
  resourceSelector:
    matchLabels: {}