namespace: observability

observabilityInstaller:
  name: cluster-observability
  tracing:
    enabled: false
    storage:
      size: 50Gi
      storageClassName: ""
      s3BucketName: ocp-cluster-observability
      s3RoleARN: arn:aws:iam::125980734123:role/AWSServiceForClusterObservability
      s3Region: us-east-1

  logging:
    enabled: false