apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.aws.credentialsSecretName }}
            namespace: {{ .Values.externalSecretsConfigNamespace }}
            key: access-key-id
          secretAccessKeySecretRef:
            name: {{ .Values.aws.credentialsSecretName }}
            namespace: {{ .Values.externalSecretsConfigNamespace }}
            key: secret-access-key