apiVersion: observability.openshift.io/v1alpha1
kind: ObservabilityInstaller
metadata:
  name: {{ .Values.observabilityInstaller.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capabilities:
    tracing:
      enabled: {{ .Values.observabilityInstaller.tracing.enabled }}
    logging:
      enabled: {{ .Values.observabilityInstaller.logging.enabled }}