apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.okta.externalSecretName }}
  namespace: {{ .Values.openshiftConfigNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.okta.externalSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        clientSecret: "{{ `{{ .clientSecret }}` }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.okta.remoteSecretKey }}
        property: {{ .Values.okta.remoteProperty }}