apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  identityProviders:
    - name: {{ .Values.okta.idpName }}
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: {{ .Values.okta.clientId | quote }}
        clientSecret:
          name: {{ .Values.okta.externalSecretName }}
        issuer: {{ .Values.okta.issuer | quote }}
        extraScopes:
          - email
          - profile
        claims:
          preferredUsername:
            - {{ .Values.oauth.preferredUsernameClaim }}
            - {{ .Values.oauth.emailClaim }}
          name:
            - {{ .Values.oauth.nameClaim }}
          email:
            - {{ .Values.oauth.emailClaim }}
          groups:
            - {{ .Values.oauth.groupsClaim }}