kiali:
  name: kiali
  namespace: istio-system
  version: default
  istioNamespace: istio-system

  deployment:
    logger:
      log_level: info
    view_only_mode: false

  external_services:
    grafana:
      enabled: false
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"

  auth:
    strategy: openshift