externalSecretsNamespace: external-secrets
externalSecretsConfigNamespace: external-secrets-config
openshiftConfigNamespace: openshift-config

aws:
  region: us-east-1
  credentialsSecretName: aws-secretsmanager-creds

secretStore:
  name: aws-secretsmanager

auth0:
  externalSecretName: auth0-client-secret
  remoteSecretKey: auth0/openshift
  remoteProperty: clientSecret
  clientId: "0hjX33cYmKOtHzxZ6ARpYSA0MfVRzWR4"
  issuer: "https://dev-drwe4kbftn75u72h.us.auth0.com"
  idpName: auth0

oauth:
  preferredUsernameClaim: email
  nameClaim: name
  emailClaim: email
  groupsClaim: groups