apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: {{ .Values.clusterMonitoring.namespace }}
data:
  config.yaml: |
    prometheusK8s:
      retention: {{ .Values.clusterMonitoring.retention }}
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: {{ .Values.clusterMonitoring.storageSize }}
{{- if .Values.clusterMonitoring.storageClassName }}
          storageClassName: {{ .Values.clusterMonitoring.storageClassName }}
{{- end }}