apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.apps.externalSecretsOperator.name }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: {{ .Values.environment | quote }}
  template:
    metadata:
      name: {{ .Values.apps.externalSecretsOperator.name }}
    spec:
      project: default
      source:
        repoURL: {{ .Values.repo.url | quote }}
        targetRevision: {{ .Values.repo.revision | quote }}
        path: {{ .Values.apps.externalSecretsOperator.chartPath | quote }}
        helm:
          valueFiles:
            - values.yaml
            - values-{{`{{ .env }}`}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .Values.apps.externalSecretsOperator.destinationNamespace | quote }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true