apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operandNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"