apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-observability-stack
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: git@github.com:madun0/cisco_ocp.git
    targetRevision: main
    path: charts/cluster-observability-stack
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: observability.openshift.io
      kind: ObservabilityInstaller
      name: cluster-observability
      namespace: observability
      jsonPointers:
        - /spec/capabilities/logging
        - /spec/capabilities/tracing/storage/size