apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-observability-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: git@github.com:madun0/cisco_ocp.git
    targetRevision: main
    path: charts/cluster-observability-operator
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cluster-observability-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true