apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/madun0/cisco_ocp.git
              revision: main
              files:
                - path: config/repo.yaml
          - git:
              repoURL: https://github.com/madun0/cisco_ocp.git
              revision: main
              files:
                - path: env/*.yaml
  template:
    metadata:
      name: external-secrets-operator
    spec:
      project: default
      source:
        repoURL: '{{ .repoURL }}'
        targetRevision: '{{ .targetRevision }}'
        path: charts/external-secrets-operator
        helm:
          valueFiles:
            - values.yaml
            - 'values-{{ .env }}.yaml'
      destination:
        server: '{{ .server }}'
        namespace: '{{ .externalSecretsNamespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  selector:
    matchExpressions:
      - key: enabled
        operator: In
        values:
          - "true"