apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  sources:
    - repoURL: https://signalfx.github.io/splunk-otel-collector-chart
      chart: splunk-otel-collector
      targetRevision: 0.145.0
      helm:
        valueFiles:
          - $values/values.yaml
          - $values/values-dev.yaml
    - repoURL: git@github.com:madun0/cisco_ocp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk-otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true