repo:
  url: https://github.com/madun0/cisco_ocp.git
  revision: main

environment: dev

apps:
  certManagerOperator:
    name: cert-manager-operator
    namespace: cert-manager-operator
    chartPath: charts/cert-manager-operator
    wave: "0"

  externalSecretsOperator:
    name: external-secrets-operator
    chartPath: charts/external-secrets-operator
    destinationNamespacePrefix: external-secrets
    wave: "1"

  auth0Idp:
    name: auth0-idp
    chartPath: charts/auth0-idp
    destinationNamespace: openshift-config
    wave: "2"
